apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-deployment
  namespace: game
  labels:
    app: farm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ap-northeast-2c
      nodeSelector:
        server: "farm"
      terminationGracePeriodSeconds: 0
      containers:
        - name: farm-container
          image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/farm:4
          volumeMounts:
            - mountPath: /testt
              name: farm-ebs-storage
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 30001     # farm server port
      volumes:
        - name: farm-ebs-storage
          persistentVolumeClaim:
            claimName: farm-pvc
