apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-cloud-deployment
  namespace: game
  labels:
    app: velocity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: server
                    operator: In
                    values:
                      - default
      nodeSelector:
        server: "default"
      terminationGracePeriodSeconds: 0
      containers:
      - name: velocity-cloud-container
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/velocity:onprem_7
        env:
        - name: ENABLE_PREFIX_DELEGATION
          value: "true"
        ports:
        - containerPort: 25565
