apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-onprem-deployment
  namespace: game
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity-onprem-container
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/velocity:onprem_4
        env:
        - name: ENABLE_PREFIX_DELEGATION
          value: "true"
        ports:
        - containerPort: 25565
