apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-onprem-deployment
  namespace: game
  labels:
    app: velocity
    argocd.argoproj.io/instance: velocity-onprem-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: server
                    operator: In
                    values:
                      - default
      nodeSelector:
        server: "default"
      terminationGracePeriodSeconds: 0
      containers:
      - name: velocity-onprem-container
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/velocity:onprem_4
        env:
        - name: ENABLE_PREFIX_DELEGATION
          value: "true"
        ports:
        - containerPort: 25565
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
